### ISSUE TITLE
is that your project can run in windows?

### ISSUE THREAD

**Issue by hsqaihkl** [ptran516/idla#2]
Hi,Ptran516
     I want to run your project in windows but your is in linux . So I added you project into VS2017 and it had erro is it (“dlib/cmd_line_parser.h”: No such file or directory) ,so I download dlib from this website （https://www.learnopencv.com/install-dlib-on-windows/）.But I met another error is ：
1.“loss_multiclass_log_lr_::compute_loss_value_and_gradient”: A heavy load function that does not find a match 
2.error C2780: “double loss_multiclass_log_lr_::compute_loss_value_and_gradient(const dlib::tensor &,const_label_iterator,SUBNET &) const”: 3 parameters should be input, but 2 are provided. 

could you help me to solve this problem?

**Comment by ptran** [comment]
@hsqaihkl make sure you're using `CMake` to build the project. 

I recommend using the `CMake` GUI ([link](https://cmake.org/runningcmake/)) to configure the project. When configuring the project using the `CMake` GUI, a VS2017 project will be generated in the directory specified in "Where to build the binaries". You should be able to use that generated project to build the code. 

Let me know if that works out.

**Comment by hsqaihkl** [comment]
@ptran516 Thank you for your reply,now I use Camke to build the VS2017 project, but one problem is that  ：
CMake Error at CMakeLists.txt:22 (message):
   DLIB_DIR must be defined as the path to dlib's root directory.

Is that need DLIB to setup in windows？

**Comment by ptran** [comment]
@hsqaihkl In the CMake GUI, you can variables using the *Add Entry* button. After clicking that, add a path variable called `DLIB_DIR` and set it to the directory where you have `dlib` downloaded to (e.g. `/home/hsqaihkl/dlib`). CMake should them be able to configure itself.

**Comment by hsqaihkl** [comment]
Ok，Thank you very much ！Follow you step I use Cmake build the project！Thanks for your help!

**Comment by hsqaihkl** [comment]
Hi，ptran516
I so sorry to bother  you. I have run your project on VS2017, but it exits instantly . and I can‘t even step through each line of code into main function.

**Comment by hsqaihkl** [comment]
I have read the code .Is that need some instructions to run into main function？
